<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TimeZoneSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement("
            INSERT INTO `time_zones` (`id`, `country_code`, `country_name`, `time_zone`, `gmt_offset`, `created_at`, `updated_at`) VALUES
	(1, 'AF', 'Afghanistan', 'Asia/Kabul', 'UTC +04:30', NULL, NULL),
	(2, 'AL', 'Albania', 'Europe/Tirane', 'UTC +01:00', NULL, NULL),
	(3, 'DZ', 'Algeria', 'Africa/Algiers', 'UTC +01:00', NULL, NULL),
	(4, 'AS', 'American Samoa', 'Pacific/Pago_Pago', 'UTC -11:00', NULL, NULL),
	(5, 'AD', 'Andorra', 'Europe/Andorra', 'UTC +01:00', NULL, NULL),
	(6, 'AO', 'Angola', 'Africa/Luanda', 'UTC +01:00', NULL, NULL),
	(7, 'AI', 'Anguilla', 'America/Anguilla', 'UTC -04:00', NULL, NULL),
	(8, 'AQ', 'Antarctica', 'Antarctica/Casey', 'UTC +11:00', NULL, NULL),
	(9, 'AQ', 'Antarctica', 'Antarctica/Davis', 'UTC +07:00', NULL, NULL),
	(10, 'AQ', 'Antarctica', 'Antarctica/DumontDUrville', 'UTC +10:00', NULL, NULL),
	(11, 'AQ', 'Antarctica', 'Antarctica/Mawson', 'UTC +05:00', NULL, NULL),
	(12, 'AQ', 'Antarctica', 'Antarctica/McMurdo', 'UTC +13:00', NULL, NULL),
	(13, 'AQ', 'Antarctica', 'Antarctica/Palmer', 'UTC -03:00', NULL, NULL),
	(14, 'AQ', 'Antarctica', 'Antarctica/Rothera', 'UTC -03:00', NULL, NULL),
	(15, 'AQ', 'Antarctica', 'Antarctica/Syowa', 'UTC +03:00', NULL, NULL),
	(16, 'AQ', 'Antarctica', 'Antarctica/Troll', 'UTC', NULL, NULL),
	(17, 'AQ', 'Antarctica', 'Antarctica/Vostok', 'UTC +06:00', NULL, NULL),
	(18, 'AG', 'Antigua and Barbuda', 'America/Antigua', 'UTC -04:00', NULL, NULL),
	(19, 'AR', 'Argentina', 'America/Argentina/Buenos_Aires', 'UTC -03:00', NULL, NULL),
	(20, 'AR', 'Argentina', 'America/Argentina/Catamarca', 'UTC -03:00', NULL, NULL),
	(21, 'AR', 'Argentina', 'America/Argentina/Cordoba', 'UTC -03:00', NULL, NULL),
	(22, 'AR', 'Argentina', 'America/Argentina/Jujuy', 'UTC -03:00', NULL, NULL),
	(23, 'AR', 'Argentina', 'America/Argentina/La_Rioja', 'UTC -03:00', NULL, NULL),
	(24, 'AR', 'Argentina', 'America/Argentina/Mendoza', 'UTC -03:00', NULL, NULL),
	(25, 'AR', 'Argentina', 'America/Argentina/Rio_Gallegos', 'UTC -03:00', NULL, NULL),
	(26, 'AR', 'Argentina', 'America/Argentina/Salta', 'UTC -03:00', NULL, NULL),
	(27, 'AR', 'Argentina', 'America/Argentina/San_Juan', 'UTC -03:00', NULL, NULL),
	(28, 'AR', 'Argentina', 'America/Argentina/San_Luis', 'UTC -03:00', NULL, NULL),
	(29, 'AR', 'Argentina', 'America/Argentina/Tucuman', 'UTC -03:00', NULL, NULL),
	(30, 'AR', 'Argentina', 'America/Argentina/Ushuaia', 'UTC -03:00', NULL, NULL),
	(31, 'AM', 'Armenia', 'Asia/Yerevan', 'UTC +04:00', NULL, NULL),
	(32, 'AW', 'Aruba', 'America/Aruba', 'UTC -04:00', NULL, NULL),
	(33, 'AU', 'Australia', 'Antarctica/Macquarie', 'UTC +11:00', NULL, NULL),
	(34, 'AU', 'Australia', 'Australia/Adelaide', 'UTC +10:30', NULL, NULL),
	(35, 'AU', 'Australia', 'Australia/Brisbane', 'UTC +10:00', NULL, NULL),
	(36, 'AU', 'Australia', 'Australia/Broken_Hill', 'UTC +10:30', NULL, NULL),
	(37, 'AU', 'Australia', 'Australia/Darwin', 'UTC +09:30', NULL, NULL),
	(38, 'AU', 'Australia', 'Australia/Eucla', 'UTC +08:45', NULL, NULL),
	(39, 'AU', 'Australia', 'Australia/Hobart', 'UTC +11:00', NULL, NULL),
	(40, 'AU', 'Australia', 'Australia/Lindeman', 'UTC +10:00', NULL, NULL),
	(41, 'AU', 'Australia', 'Australia/Lord_Howe', 'UTC +11:00', NULL, NULL),
	(42, 'AU', 'Australia', 'Australia/Melbourne', 'UTC +11:00', NULL, NULL),
	(43, 'AU', 'Australia', 'Australia/Perth', 'UTC +08:00', NULL, NULL),
	(44, 'AU', 'Australia', 'Australia/Sydney', 'UTC +11:00', NULL, NULL),
	(45, 'AT', 'Austria', 'Europe/Vienna', 'UTC +01:00', NULL, NULL),
	(46, 'AZ', 'Azerbaijan', 'Asia/Baku', 'UTC +04:00', NULL, NULL),
	(47, 'BS', 'Bahamas', 'America/Nassau', 'UTC -05:00', NULL, NULL),
	(48, 'BH', 'Bahrain', 'Asia/Bahrain', 'UTC +03:00', NULL, NULL),
	(49, 'BD', 'Bangladesh', 'Asia/Dhaka', 'UTC +06:00', NULL, NULL),
	(50, 'BB', 'Barbados', 'America/Barbados', 'UTC -04:00', NULL, NULL),
	(51, 'BY', 'Belarus', 'Europe/Minsk', 'UTC +03:00', NULL, NULL),
	(52, 'BE', 'Belgium', 'Europe/Brussels', 'UTC +01:00', NULL, NULL),
	(53, 'BZ', 'Belize', 'America/Belize', 'UTC -06:00', NULL, NULL),
	(54, 'BJ', 'Benin', 'Africa/Porto-Novo', 'UTC +01:00', NULL, NULL),
	(55, 'BM', 'Bermuda', 'Atlantic/Bermuda', 'UTC -04:00', NULL, NULL),
	(56, 'BT', 'Bhutan', 'Asia/Thimphu', 'UTC +06:00', NULL, NULL),
	(57, 'BO', 'Bolivia, Plurinational State of', 'America/La_Paz', 'UTC -04:00', NULL, NULL),
	(58, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'America/Kralendijk', 'UTC -04:00', NULL, NULL),
	(59, 'BA', 'Bosnia and Herzegovina', 'Europe/Sarajevo', 'UTC +01:00', NULL, NULL),
	(60, 'BW', 'Botswana', 'Africa/Gaborone', 'UTC +02:00', NULL, NULL),
	(61, 'BR', 'Brazil', 'America/Araguaina', 'UTC -03:00', NULL, NULL),
	(62, 'BR', 'Brazil', 'America/Bahia', 'UTC -03:00', NULL, NULL),
	(63, 'BR', 'Brazil', 'America/Belem', 'UTC -03:00', NULL, NULL),
	(64, 'BR', 'Brazil', 'America/Boa_Vista', 'UTC -04:00', NULL, NULL),
	(65, 'BR', 'Brazil', 'America/Campo_Grande', 'UTC -04:00', NULL, NULL),
	(66, 'BR', 'Brazil', 'America/Cuiaba', 'UTC -04:00', NULL, NULL),
	(67, 'BR', 'Brazil', 'America/Eirunepe', 'UTC -05:00', NULL, NULL),
	(68, 'BR', 'Brazil', 'America/Fortaleza', 'UTC -03:00', NULL, NULL),
	(69, 'BR', 'Brazil', 'America/Maceio', 'UTC -03:00', NULL, NULL),
	(70, 'BR', 'Brazil', 'America/Manaus', 'UTC -04:00', NULL, NULL),
	(71, 'BR', 'Brazil', 'America/Noronha', 'UTC -02:00', NULL, NULL),
	(72, 'BR', 'Brazil', 'America/Porto_Velho', 'UTC -04:00', NULL, NULL),
	(73, 'BR', 'Brazil', 'America/Recife', 'UTC -03:00', NULL, NULL),
	(74, 'BR', 'Brazil', 'America/Rio_Branco', 'UTC -05:00', NULL, NULL),
	(75, 'BR', 'Brazil', 'America/Santarem', 'UTC -03:00', NULL, NULL),
	(76, 'BR', 'Brazil', 'America/Sao_Paulo', 'UTC -03:00', NULL, NULL),
	(77, 'IO', 'British Indian Ocean Territory', 'Indian/Chagos', 'UTC +06:00', NULL, NULL),
	(78, 'BN', 'Brunei Darussalam', 'Asia/Brunei', 'UTC +08:00', NULL, NULL),
	(79, 'BG', 'Bulgaria', 'Europe/Sofia', 'UTC +02:00', NULL, NULL),
	(80, 'BF', 'Burkina Faso', 'Africa/Ouagadougou', 'UTC', NULL, NULL),
	(81, 'BI', 'Burundi', 'Africa/Bujumbura', 'UTC +02:00', NULL, NULL),
	(82, 'KH', 'Cambodia', 'Asia/Phnom_Penh', 'UTC +07:00', NULL, NULL),
	(83, 'CM', 'Cameroon', 'Africa/Douala', 'UTC +01:00', NULL, NULL),
	(84, 'CA', 'Canada', 'America/Atikokan', 'UTC -05:00', NULL, NULL),
	(85, 'CA', 'Canada', 'America/Blanc-Sablon', 'UTC -04:00', NULL, NULL),
	(86, 'CA', 'Canada', 'America/Cambridge_Bay', 'UTC -07:00', NULL, NULL),
	(87, 'CA', 'Canada', 'America/Creston', 'UTC -07:00', NULL, NULL),
	(88, 'CA', 'Canada', 'America/Dawson', 'UTC -07:00', NULL, NULL),
	(89, 'CA', 'Canada', 'America/Dawson_Creek', 'UTC -07:00', NULL, NULL),
	(90, 'CA', 'Canada', 'America/Edmonton', 'UTC -07:00', NULL, NULL),
	(91, 'CA', 'Canada', 'America/Fort_Nelson', 'UTC -07:00', NULL, NULL),
	(92, 'CA', 'Canada', 'America/Glace_Bay', 'UTC -04:00', NULL, NULL),
	(93, 'CA', 'Canada', 'America/Goose_Bay', 'UTC -04:00', NULL, NULL),
	(94, 'CA', 'Canada', 'America/Halifax', 'UTC -04:00', NULL, NULL),
	(95, 'CA', 'Canada', 'America/Inuvik', 'UTC -07:00', NULL, NULL),
	(96, 'CA', 'Canada', 'America/Iqaluit', 'UTC -05:00', NULL, NULL),
	(97, 'CA', 'Canada', 'America/Moncton', 'UTC -04:00', NULL, NULL),
	(98, 'CA', 'Canada', 'America/Rankin_Inlet', 'UTC -06:00', NULL, NULL),
	(99, 'CA', 'Canada', 'America/Regina', 'UTC -06:00', NULL, NULL),
	(100, 'CA', 'Canada', 'America/Resolute', 'UTC -06:00', NULL, NULL),
	(101, 'CA', 'Canada', 'America/St_Johns', 'UTC -03:30', NULL, NULL),
	(102, 'CA', 'Canada', 'America/Swift_Current', 'UTC -06:00', NULL, NULL),
	(103, 'CA', 'Canada', 'America/Toronto', 'UTC -05:00', NULL, NULL),
	(104, 'CA', 'Canada', 'America/Vancouver', 'UTC -08:00', NULL, NULL),
	(105, 'CA', 'Canada', 'America/Whitehorse', 'UTC -07:00', NULL, NULL),
	(106, 'CA', 'Canada', 'America/Winnipeg', 'UTC -06:00', NULL, NULL),
	(107, 'CA', 'Canada', 'America/Yellowknife', 'UTC -07:00', NULL, NULL),
	(108, 'CV', 'Cape Verde', 'Atlantic/Cape_Verde', 'UTC -01:00', NULL, NULL),
	(109, 'KY', 'Cayman Islands', 'America/Cayman', 'UTC -05:00', NULL, NULL),
	(110, 'CF', 'Central African Republic', 'Africa/Bangui', 'UTC +01:00', NULL, NULL),
	(111, 'TD', 'Chad', 'Africa/Ndjamena', 'UTC +01:00', NULL, NULL),
	(112, 'CL', 'Chile', 'America/Punta_Arenas', 'UTC -03:00', NULL, NULL),
	(113, 'CL', 'Chile', 'America/Santiago', 'UTC -03:00', NULL, NULL),
	(114, 'CL', 'Chile', 'Pacific/Easter', 'UTC -05:00', NULL, NULL),
	(115, 'CN', 'China', 'Asia/Shanghai', 'UTC +08:00', NULL, NULL),
	(116, 'CN', 'China', 'Asia/Urumqi', 'UTC +06:00', NULL, NULL),
	(117, 'CX', 'Christmas Island', 'Indian/Christmas', 'UTC +07:00', NULL, NULL),
	(118, 'CC', 'Cocos (Keeling) Islands', 'Indian/Cocos', 'UTC +06:30', NULL, NULL),
	(119, 'CO', 'Colombia', 'America/Bogota', 'UTC -05:00', NULL, NULL),
	(120, 'KM', 'Comoros', 'Indian/Comoro', 'UTC +03:00', NULL, NULL),
	(121, 'CG', 'Congo', 'Africa/Brazzaville', 'UTC +01:00', NULL, NULL),
	(122, 'CD', 'Congo, the Democratic Republic of the', 'Africa/Kinshasa', 'UTC +01:00', NULL, NULL),
	(123, 'CD', 'Congo, the Democratic Republic of the', 'Africa/Lubumbashi', 'UTC +02:00', NULL, NULL),
	(124, 'CK', 'Cook Islands', 'Pacific/Rarotonga', 'UTC -10:00', NULL, NULL),
	(125, 'CR', 'Costa Rica', 'America/Costa_Rica', 'UTC -06:00', NULL, NULL),
	(126, 'HR', 'Croatia', 'Europe/Zagreb', 'UTC +01:00', NULL, NULL),
	(127, 'CU', 'Cuba', 'America/Havana', 'UTC -05:00', NULL, NULL),
	(128, 'CW', 'Curaçao', 'America/Curacao', 'UTC -04:00', NULL, NULL),
	(129, 'CY', 'Cyprus', 'Asia/Famagusta', 'UTC +02:00', NULL, NULL),
	(130, 'CY', 'Cyprus', 'Asia/Nicosia', 'UTC +02:00', NULL, NULL),
	(131, 'CZ', 'Czech Republic', 'Europe/Prague', 'UTC +01:00', NULL, NULL),
	(132, 'CI', 'Côte d\'Ivoire', 'Africa/Abidjan', 'UTC', NULL, NULL),
	(133, 'DK', 'Denmark', 'Europe/Copenhagen', 'UTC +01:00', NULL, NULL),
	(134, 'DJ', 'Djibouti', 'Africa/Djibouti', 'UTC +03:00', NULL, NULL),
	(135, 'DM', 'Dominica', 'America/Dominica', 'UTC -04:00', NULL, NULL),
	(136, 'DO', 'Dominican Republic', 'America/Santo_Domingo', 'UTC -04:00', NULL, NULL),
	(137, 'EC', 'Ecuador', 'America/Guayaquil', 'UTC -05:00', NULL, NULL),
	(138, 'EC', 'Ecuador', 'Pacific/Galapagos', 'UTC -06:00', NULL, NULL),
	(139, 'EG', 'Egypt', 'Africa/Cairo', 'UTC +02:00', NULL, NULL),
	(140, 'SV', 'El Salvador', 'America/El_Salvador', 'UTC -06:00', NULL, NULL),
	(141, 'GQ', 'Equatorial Guinea', 'Africa/Malabo', 'UTC +01:00', NULL, NULL),
	(142, 'ER', 'Eritrea', 'Africa/Asmara', 'UTC +03:00', NULL, NULL),
	(143, 'EE', 'Estonia', 'Europe/Tallinn', 'UTC +02:00', NULL, NULL),
	(144, 'ET', 'Ethiopia', 'Africa/Addis_Ababa', 'UTC +03:00', NULL, NULL),
	(145, 'FK', 'Falkland Islands (Malvinas)', 'Atlantic/Stanley', 'UTC -03:00', NULL, NULL),
	(146, 'FO', 'Faroe Islands', 'Atlantic/Faroe', 'UTC', NULL, NULL),
	(147, 'FJ', 'Fiji', 'Pacific/Fiji', 'UTC +12:00', NULL, NULL),
	(148, 'FI', 'Finland', 'Europe/Helsinki', 'UTC +02:00', NULL, NULL),
	(149, 'FR', 'France', 'Europe/Paris', 'UTC +01:00', NULL, NULL),
	(150, 'GF', 'French Guiana', 'America/Cayenne', 'UTC -03:00', NULL, NULL),
	(151, 'PF', 'French Polynesia', 'Pacific/Gambier', 'UTC -09:00', NULL, NULL),
	(152, 'PF', 'French Polynesia', 'Pacific/Marquesas', 'UTC -09:30', NULL, NULL),
	(153, 'PF', 'French Polynesia', 'Pacific/Tahiti', 'UTC -10:00', NULL, NULL),
	(154, 'TF', 'French Southern Territories', 'Indian/Kerguelen', 'UTC +05:00', NULL, NULL),
	(155, 'GA', 'Gabon', 'Africa/Libreville', 'UTC +01:00', NULL, NULL),
	(156, 'GM', 'Gambia', 'Africa/Banjul', 'UTC', NULL, NULL),
	(157, 'GE', 'Georgia', 'Asia/Tbilisi', 'UTC +04:00', NULL, NULL),
	(158, 'DE', 'Germany', 'Europe/Berlin', 'UTC +01:00', NULL, NULL),
	(159, 'DE', 'Germany', 'Europe/Busingen', 'UTC +01:00', NULL, NULL),
	(160, 'GH', 'Ghana', 'Africa/Accra', 'UTC', NULL, NULL),
	(161, 'GI', 'Gibraltar', 'Europe/Gibraltar', 'UTC +01:00', NULL, NULL),
	(162, 'GR', 'Greece', 'Europe/Athens', 'UTC +02:00', NULL, NULL),
	(163, 'GL', 'Greenland', 'America/Danmarkshavn', 'UTC', NULL, NULL),
	(164, 'GL', 'Greenland', 'America/Nuuk', 'UTC -03:00', NULL, NULL),
	(165, 'GL', 'Greenland', 'America/Scoresbysund', 'UTC -01:00', NULL, NULL),
	(166, 'GL', 'Greenland', 'America/Thule', 'UTC -04:00', NULL, NULL),
	(167, 'GD', 'Grenada', 'America/Grenada', 'UTC -04:00', NULL, NULL),
	(168, 'GP', 'Guadeloupe', 'America/Guadeloupe', 'UTC -04:00', NULL, NULL),
	(169, 'GU', 'Guam', 'Pacific/Guam', 'UTC +10:00', NULL, NULL),
	(170, 'GT', 'Guatemala', 'America/Guatemala', 'UTC -06:00', NULL, NULL),
	(171, 'GG', 'Guernsey', 'Europe/Guernsey', 'UTC', NULL, NULL),
	(172, 'GN', 'Guinea', 'Africa/Conakry', 'UTC', NULL, NULL),
	(173, 'GW', 'Guinea-Bissau', 'Africa/Bissau', 'UTC', NULL, NULL),
	(174, 'GY', 'Guyana', 'America/Guyana', 'UTC -04:00', NULL, NULL),
	(175, 'HT', 'Haiti', 'America/Port-au-Prince', 'UTC -05:00', NULL, NULL),
	(176, 'VA', 'Holy See (Vatican City State)', 'Europe/Vatican', 'UTC +01:00', NULL, NULL),
	(177, 'HN', 'Honduras', 'America/Tegucigalpa', 'UTC -06:00', NULL, NULL),
	(178, 'HK', 'Hong Kong', 'Asia/Hong_Kong', 'UTC +08:00', NULL, NULL),
	(179, 'HU', 'Hungary', 'Europe/Budapest', 'UTC +01:00', NULL, NULL),
	(180, 'IS', 'Iceland', 'Atlantic/Reykjavik', 'UTC', NULL, NULL),
	(181, 'IN', 'India', 'Asia/Kolkata', 'UTC +05:30', NULL, NULL),
	(182, 'ID', 'Indonesia', 'Asia/Jakarta', 'UTC +07:00', NULL, NULL),
	(183, 'ID', 'Indonesia', 'Asia/Jayapura', 'UTC +09:00', NULL, NULL),
	(184, 'ID', 'Indonesia', 'Asia/Makassar', 'UTC +08:00', NULL, NULL),
	(185, 'ID', 'Indonesia', 'Asia/Pontianak', 'UTC +07:00', NULL, NULL),
	(186, 'IR', 'Iran, Islamic Republic of', 'Asia/Tehran', 'UTC +03:30', NULL, NULL),
	(187, 'IQ', 'Iraq', 'Asia/Baghdad', 'UTC +03:00', NULL, NULL),
	(188, 'IE', 'Ireland', 'Europe/Dublin', 'UTC', NULL, NULL),
	(189, 'IM', 'Isle of Man', 'Europe/Isle_of_Man', 'UTC', NULL, NULL),
	(190, 'IL', 'Israel', 'Asia/Jerusalem', 'UTC +02:00', NULL, NULL),
	(191, 'IT', 'Italy', 'Europe/Rome', 'UTC +01:00', NULL, NULL),
	(192, 'JM', 'Jamaica', 'America/Jamaica', 'UTC -05:00', NULL, NULL),
	(193, 'JP', 'Japan', 'Asia/Tokyo', 'UTC +09:00', NULL, NULL),
	(194, 'JE', 'Jersey', 'Europe/Jersey', 'UTC', NULL, NULL),
	(195, 'JO', 'Jordan', 'Asia/Amman', 'UTC +03:00', NULL, NULL),
	(196, 'KZ', 'Kazakhstan', 'Asia/Almaty', 'UTC +06:00', NULL, NULL),
	(197, 'KZ', 'Kazakhstan', 'Asia/Aqtau', 'UTC +05:00', NULL, NULL),
	(198, 'KZ', 'Kazakhstan', 'Asia/Aqtobe', 'UTC +05:00', NULL, NULL),
	(199, 'KZ', 'Kazakhstan', 'Asia/Atyrau', 'UTC +05:00', NULL, NULL),
	(200, 'KZ', 'Kazakhstan', 'Asia/Oral', 'UTC +05:00', NULL, NULL),
	(201, 'KZ', 'Kazakhstan', 'Asia/Qostanay', 'UTC +06:00', NULL, NULL),
	(202, 'KZ', 'Kazakhstan', 'Asia/Qyzylorda', 'UTC +05:00', NULL, NULL),
	(203, 'KE', 'Kenya', 'Africa/Nairobi', 'UTC +03:00', NULL, NULL),
	(204, 'KI', 'Kiribati', 'Pacific/Kanton', 'UTC +13:00', NULL, NULL),
	(205, 'KI', 'Kiribati', 'Pacific/Kiritimati', 'UTC +14:00', NULL, NULL),
	(206, 'KI', 'Kiribati', 'Pacific/Tarawa', 'UTC +12:00', NULL, NULL),
	(207, 'KP', 'Korea, Democratic People\'s Republic of', 'Asia/Pyongyang', 'UTC +09:00', NULL, NULL),
	(208, 'KR', 'Korea, Republic of', 'Asia/Seoul', 'UTC +09:00', NULL, NULL),
	(209, 'KW', 'Kuwait', 'Asia/Kuwait', 'UTC +03:00', NULL, NULL),
	(210, 'KG', 'Kyrgyzstan', 'Asia/Bishkek', 'UTC +06:00', NULL, NULL),
	(211, 'LA', 'Lao People\'s Democratic Republic', 'Asia/Vientiane', 'UTC +07:00', NULL, NULL),
	(212, 'LV', 'Latvia', 'Europe/Riga', 'UTC +02:00', NULL, NULL),
	(213, 'LB', 'Lebanon', 'Asia/Beirut', 'UTC +02:00', NULL, NULL),
	(214, 'LS', 'Lesotho', 'Africa/Maseru', 'UTC +02:00', NULL, NULL),
	(215, 'LR', 'Liberia', 'Africa/Monrovia', 'UTC', NULL, NULL),
	(216, 'LY', 'Libya', 'Africa/Tripoli', 'UTC +02:00', NULL, NULL),
	(217, 'LI', 'Liechtenstein', 'Europe/Vaduz', 'UTC +01:00', NULL, NULL),
	(218, 'LT', 'Lithuania', 'Europe/Vilnius', 'UTC +02:00', NULL, NULL),
	(219, 'LU', 'Luxembourg', 'Europe/Luxembourg', 'UTC +01:00', NULL, NULL),
	(220, 'MO', 'Macao', 'Asia/Macau', 'UTC +08:00', NULL, NULL),
	(221, 'MK', 'Macedonia, the Former Yugoslav Republic of', 'Europe/Skopje', 'UTC +01:00', NULL, NULL),
	(222, 'MG', 'Madagascar', 'Indian/Antananarivo', 'UTC +03:00', NULL, NULL),
	(223, 'MW', 'Malawi', 'Africa/Blantyre', 'UTC +02:00', NULL, NULL),
	(224, 'MY', 'Malaysia', 'Asia/Kuala_Lumpur', 'UTC +08:00', NULL, NULL),
	(225, 'MY', 'Malaysia', 'Asia/Kuching', 'UTC +08:00', NULL, NULL),
	(226, 'MV', 'Maldives', 'Indian/Maldives', 'UTC +05:00', NULL, NULL),
	(227, 'ML', 'Mali', 'Africa/Bamako', 'UTC', NULL, NULL),
	(228, 'MT', 'Malta', 'Europe/Malta', 'UTC +01:00', NULL, NULL),
	(229, 'MH', 'Marshall Islands', 'Pacific/Kwajalein', 'UTC +12:00', NULL, NULL),
	(230, 'MH', 'Marshall Islands', 'Pacific/Majuro', 'UTC +12:00', NULL, NULL),
	(231, 'MQ', 'Martinique', 'America/Martinique', 'UTC -04:00', NULL, NULL),
	(232, 'MR', 'Mauritania', 'Africa/Nouakchott', 'UTC', NULL, NULL),
	(233, 'MU', 'Mauritius', 'Indian/Mauritius', 'UTC +04:00', NULL, NULL),
	(234, 'YT', 'Mayotte', 'Indian/Mayotte', 'UTC +03:00', NULL, NULL),
	(235, 'MX', 'Mexico', 'America/Bahia_Banderas', 'UTC -06:00', NULL, NULL),
	(236, 'MX', 'Mexico', 'America/Cancun', 'UTC -05:00', NULL, NULL),
	(237, 'MX', 'Mexico', 'America/Chihuahua', 'UTC -06:00', NULL, NULL),
	(238, 'MX', 'Mexico', 'America/Ciudad_Juarez', 'UTC -07:00', NULL, NULL),
	(239, 'MX', 'Mexico', 'America/Hermosillo', 'UTC -07:00', NULL, NULL),
	(240, 'MX', 'Mexico', 'America/Matamoros', 'UTC -06:00', NULL, NULL),
	(241, 'MX', 'Mexico', 'America/Mazatlan', 'UTC -07:00', NULL, NULL),
	(242, 'MX', 'Mexico', 'America/Merida', 'UTC -06:00', NULL, NULL),
	(243, 'MX', 'Mexico', 'America/Mexico_City', 'UTC -06:00', NULL, NULL),
	(244, 'MX', 'Mexico', 'America/Monterrey', 'UTC -06:00', NULL, NULL),
	(245, 'MX', 'Mexico', 'America/Ojinaga', 'UTC -06:00', NULL, NULL),
	(246, 'MX', 'Mexico', 'America/Tijuana', 'UTC -08:00', NULL, NULL),
	(247, 'FM', 'Micronesia, Federated States of', 'Pacific/Chuuk', 'UTC +10:00', NULL, NULL),
	(248, 'FM', 'Micronesia, Federated States of', 'Pacific/Kosrae', 'UTC +11:00', NULL, NULL),
	(249, 'FM', 'Micronesia, Federated States of', 'Pacific/Pohnpei', 'UTC +11:00', NULL, NULL),
	(250, 'MD', 'Moldova, Republic of', 'Europe/Chisinau', 'UTC +02:00', NULL, NULL),
	(251, 'MC', 'Monaco', 'Europe/Monaco', 'UTC +01:00', NULL, NULL),
	(252, 'MN', 'Mongolia', 'Asia/Choibalsan', 'UTC +08:00', NULL, NULL),
	(253, 'MN', 'Mongolia', 'Asia/Hovd', 'UTC +07:00', NULL, NULL),
	(254, 'MN', 'Mongolia', 'Asia/Ulaanbaatar', 'UTC +08:00', NULL, NULL),
	(255, 'ME', 'Montenegro', 'Europe/Podgorica', 'UTC +01:00', NULL, NULL),
	(256, 'MS', 'Montserrat', 'America/Montserrat', 'UTC -04:00', NULL, NULL),
	(257, 'MA', 'Morocco', 'Africa/Casablanca', 'UTC +01:00', NULL, NULL),
	(258, 'MA', 'Morocco', 'Africa/El_Aaiun', 'UTC +01:00', NULL, NULL),
	(259, 'MZ', 'Mozambique', 'Africa/Maputo', 'UTC +02:00', NULL, NULL),
	(260, 'MM', 'Myanmar', 'Asia/Yangon', 'UTC +06:30', NULL, NULL),
	(261, 'NA', 'Namibia', 'Africa/Windhoek', 'UTC +02:00', NULL, NULL),
	(262, 'NR', 'Nauru', 'Pacific/Nauru', 'UTC +12:00', NULL, NULL),
	(263, 'NP', 'Nepal', 'Asia/Kathmandu', 'UTC +05:45', NULL, NULL),
	(264, 'NL', 'Netherlands', 'Europe/Amsterdam', 'UTC +01:00', NULL, NULL),
	(265, 'NC', 'New Caledonia', 'Pacific/Noumea', 'UTC +11:00', NULL, NULL),
	(266, 'NZ', 'New Zealand', 'Pacific/Auckland', 'UTC +13:00', NULL, NULL),
	(267, 'NZ', 'New Zealand', 'Pacific/Chatham', 'UTC +13:45', NULL, NULL),
	(268, 'NI', 'Nicaragua', 'America/Managua', 'UTC -06:00', NULL, NULL),
	(269, 'NE', 'Niger', 'Africa/Niamey', 'UTC +01:00', NULL, NULL),
	(270, 'NG', 'Nigeria', 'Africa/Lagos', 'UTC +01:00', NULL, NULL),
	(271, 'NU', 'Niue', 'Pacific/Niue', 'UTC -11:00', NULL, NULL),
	(272, 'NF', 'Norfolk Island', 'Pacific/Norfolk', 'UTC +12:00', NULL, NULL),
	(273, 'MP', 'Northern Mariana Islands', 'Pacific/Saipan', 'UTC +10:00', NULL, NULL),
	(274, 'NO', 'Norway', 'Europe/Oslo', 'UTC +01:00', NULL, NULL),
	(275, 'OM', 'Oman', 'Asia/Muscat', 'UTC +04:00', NULL, NULL),
	(276, 'PK', 'Pakistan', 'Asia/Karachi', 'UTC +05:00', NULL, NULL),
	(277, 'PW', 'Palau', 'Pacific/Palau', 'UTC +09:00', NULL, NULL),
	(278, 'PS', 'Palestine, State of', 'Asia/Gaza', 'UTC +02:00', NULL, NULL),
	(279, 'PS', 'Palestine, State of', 'Asia/Hebron', 'UTC +02:00', NULL, NULL),
	(280, 'PA', 'Panama', 'America/Panama', 'UTC -05:00', NULL, NULL),
	(281, 'PG', 'Papua New Guinea', 'Pacific/Bougainville', 'UTC +11:00', NULL, NULL),
	(282, 'PG', 'Papua New Guinea', 'Pacific/Port_Moresby', 'UTC +10:00', NULL, NULL),
	(283, 'PY', 'Paraguay', 'America/Asuncion', 'UTC -03:00', NULL, NULL),
	(284, 'PE', 'Peru', 'America/Lima', 'UTC -05:00', NULL, NULL),
	(285, 'PH', 'Philippines', 'Asia/Manila', 'UTC +08:00', NULL, NULL),
	(286, 'PN', 'Pitcairn', 'Pacific/Pitcairn', 'UTC -08:00', NULL, NULL),
	(287, 'PL', 'Poland', 'Europe/Warsaw', 'UTC +01:00', NULL, NULL),
	(288, 'PT', 'Portugal', 'Atlantic/Azores', 'UTC -01:00', NULL, NULL),
	(289, 'PT', 'Portugal', 'Atlantic/Madeira', 'UTC', NULL, NULL),
	(290, 'PT', 'Portugal', 'Europe/Lisbon', 'UTC', NULL, NULL),
	(291, 'PR', 'Puerto Rico', 'America/Puerto_Rico', 'UTC -04:00', NULL, NULL),
	(292, 'QA', 'Qatar', 'Asia/Qatar', 'UTC +03:00', NULL, NULL),
	(293, 'RO', 'Romania', 'Europe/Bucharest', 'UTC +02:00', NULL, NULL),
	(294, 'RU', 'Russian Federation', 'Asia/Anadyr', 'UTC +12:00', NULL, NULL),
	(295, 'RU', 'Russian Federation', 'Asia/Barnaul', 'UTC +07:00', NULL, NULL),
	(296, 'RU', 'Russian Federation', 'Asia/Chita', 'UTC +09:00', NULL, NULL),
	(297, 'RU', 'Russian Federation', 'Asia/Irkutsk', 'UTC +08:00', NULL, NULL),
	(298, 'RU', 'Russian Federation', 'Asia/Kamchatka', 'UTC +12:00', NULL, NULL),
	(299, 'RU', 'Russian Federation', 'Asia/Khandyga', 'UTC +09:00', NULL, NULL),
	(300, 'RU', 'Russian Federation', 'Asia/Krasnoyarsk', 'UTC +07:00', NULL, NULL),
	(301, 'RU', 'Russian Federation', 'Asia/Magadan', 'UTC +11:00', NULL, NULL),
	(302, 'RU', 'Russian Federation', 'Asia/Novokuznetsk', 'UTC +07:00', NULL, NULL),
	(303, 'RU', 'Russian Federation', 'Asia/Novosibirsk', 'UTC +07:00', NULL, NULL),
	(304, 'RU', 'Russian Federation', 'Asia/Omsk', 'UTC +06:00', NULL, NULL),
	(305, 'RU', 'Russian Federation', 'Asia/Sakhalin', 'UTC +11:00', NULL, NULL),
	(306, 'RU', 'Russian Federation', 'Asia/Srednekolymsk', 'UTC +11:00', NULL, NULL),
	(307, 'RU', 'Russian Federation', 'Asia/Tomsk', 'UTC +07:00', NULL, NULL),
	(308, 'RU', 'Russian Federation', 'Asia/Ust-Nera', 'UTC +10:00', NULL, NULL),
	(309, 'RU', 'Russian Federation', 'Asia/Vladivostok', 'UTC +10:00', NULL, NULL),
	(310, 'RU', 'Russian Federation', 'Asia/Yakutsk', 'UTC +09:00', NULL, NULL),
	(311, 'RU', 'Russian Federation', 'Asia/Yekaterinburg', 'UTC +05:00', NULL, NULL),
	(312, 'RU', 'Russian Federation', 'Europe/Astrakhan', 'UTC +04:00', NULL, NULL),
	(313, 'RU', 'Russian Federation', 'Europe/Kaliningrad', 'UTC +02:00', NULL, NULL),
	(314, 'RU', 'Russian Federation', 'Europe/Kirov', 'UTC +03:00', NULL, NULL),
	(315, 'RU', 'Russian Federation', 'Europe/Moscow', 'UTC +03:00', NULL, NULL),
	(316, 'RU', 'Russian Federation', 'Europe/Samara', 'UTC +04:00', NULL, NULL),
	(317, 'RU', 'Russian Federation', 'Europe/Saratov', 'UTC +04:00', NULL, NULL),
	(318, 'RU', 'Russian Federation', 'Europe/Ulyanovsk', 'UTC +04:00', NULL, NULL),
	(319, 'RU', 'Russian Federation', 'Europe/Volgograd', 'UTC +03:00', NULL, NULL),
	(320, 'RW', 'Rwanda', 'Africa/Kigali', 'UTC +02:00', NULL, NULL),
	(321, 'RE', 'Réunion', 'Indian/Reunion', 'UTC +04:00', NULL, NULL),
	(322, 'BL', 'Saint Barthélemy', 'America/St_Barthelemy', 'UTC -04:00', NULL, NULL),
	(323, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Atlantic/St_Helena', 'UTC', NULL, NULL),
	(324, 'KN', 'Saint Kitts and Nevis', 'America/St_Kitts', 'UTC -04:00', NULL, NULL),
	(325, 'LC', 'Saint Lucia', 'America/St_Lucia', 'UTC -04:00', NULL, NULL),
	(326, 'MF', 'Saint Martin (French part)', 'America/Marigot', 'UTC -04:00', NULL, NULL),
	(327, 'PM', 'Saint Pierre and Miquelon', 'America/Miquelon', 'UTC -03:00', NULL, NULL),
	(328, 'VC', 'Saint Vincent and the Grenadines', 'America/St_Vincent', 'UTC -04:00', NULL, NULL),
	(329, 'WS', 'Samoa', 'Pacific/Apia', 'UTC +13:00', NULL, NULL),
	(330, 'SM', 'San Marino', 'Europe/San_Marino', 'UTC +01:00', NULL, NULL),
	(331, 'ST', 'Sao Tome and Principe', 'Africa/Sao_Tome', 'UTC', NULL, NULL),
	(332, 'SA', 'Saudi Arabia', 'Asia/Riyadh', 'UTC +03:00', NULL, NULL),
	(333, 'SN', 'Senegal', 'Africa/Dakar', 'UTC', NULL, NULL),
	(334, 'RS', 'Serbia', 'Europe/Belgrade', 'UTC +01:00', NULL, NULL),
	(335, 'SC', 'Seychelles', 'Indian/Mahe', 'UTC +04:00', NULL, NULL),
	(336, 'SL', 'Sierra Leone', 'Africa/Freetown', 'UTC', NULL, NULL),
	(337, 'SG', 'Singapore', 'Asia/Singapore', 'UTC +08:00', NULL, NULL),
	(338, 'SX', 'Sint Maarten (Dutch part)', 'America/Lower_Princes', 'UTC -04:00', NULL, NULL),
	(339, 'SK', 'Slovakia', 'Europe/Bratislava', 'UTC +01:00', NULL, NULL),
	(340, 'SI', 'Slovenia', 'Europe/Ljubljana', 'UTC +01:00', NULL, NULL),
	(341, 'SB', 'Solomon Islands', 'Pacific/Guadalcanal', 'UTC +11:00', NULL, NULL),
	(342, 'SO', 'Somalia', 'Africa/Mogadishu', 'UTC +03:00', NULL, NULL),
	(343, 'ZA', 'South Africa', 'Africa/Johannesburg', 'UTC +02:00', NULL, NULL),
	(344, 'GS', 'South Georgia and the South Sandwich Islands', 'Atlantic/South_Georgia', 'UTC -02:00', NULL, NULL),
	(345, 'SS', 'South Sudan', 'Africa/Juba', 'UTC +02:00', NULL, NULL),
	(346, 'ES', 'Spain', 'Africa/Ceuta', 'UTC +01:00', NULL, NULL),
	(347, 'ES', 'Spain', 'Atlantic/Canary', 'UTC', NULL, NULL),
	(348, 'ES', 'Spain', 'Europe/Madrid', 'UTC +01:00', NULL, NULL),
	(349, 'LK', 'Sri Lanka', 'Asia/Colombo', 'UTC +05:30', NULL, NULL),
	(350, 'SD', 'Sudan', 'Africa/Khartoum', 'UTC +02:00', NULL, NULL),
	(351, 'SR', 'Suriname', 'America/Paramaribo', 'UTC -03:00', NULL, NULL),
	(352, 'SJ', 'Svalbard and Jan Mayen', 'Arctic/Longyearbyen', 'UTC +01:00', NULL, NULL),
	(353, 'SZ', 'Swaziland', 'Africa/Mbabane', 'UTC +02:00', NULL, NULL),
	(354, 'SE', 'Sweden', 'Europe/Stockholm', 'UTC +01:00', NULL, NULL),
	(355, 'CH', 'Switzerland', 'Europe/Zurich', 'UTC +01:00', NULL, NULL),
	(356, 'SY', 'Syrian Arab Republic', 'Asia/Damascus', 'UTC +03:00', NULL, NULL),
	(357, 'TW', 'Taiwan, Province of China', 'Asia/Taipei', 'UTC +08:00', NULL, NULL),
	(358, 'TJ', 'Tajikistan', 'Asia/Dushanbe', 'UTC +05:00', NULL, NULL),
	(359, 'TZ', 'Tanzania, United Republic of', 'Africa/Dar_es_Salaam', 'UTC +03:00', NULL, NULL),
	(360, 'TH', 'Thailand', 'Asia/Bangkok', 'UTC +07:00', NULL, NULL),
	(361, 'TL', 'Timor-Leste', 'Asia/Dili', 'UTC +09:00', NULL, NULL),
	(362, 'TG', 'Togo', 'Africa/Lome', 'UTC', NULL, NULL),
	(363, 'TK', 'Tokelau', 'Pacific/Fakaofo', 'UTC +13:00', NULL, NULL),
	(364, 'TO', 'Tonga', 'Pacific/Tongatapu', 'UTC +13:00', NULL, NULL),
	(365, 'TT', 'Trinidad and Tobago', 'America/Port_of_Spain', 'UTC -04:00', NULL, NULL),
	(366, 'TN', 'Tunisia', 'Africa/Tunis', 'UTC +01:00', NULL, NULL),
	(367, 'TR', 'Turkey', 'Europe/Istanbul', 'UTC +03:00', NULL, NULL),
	(368, 'TM', 'Turkmenistan', 'Asia/Ashgabat', 'UTC +05:00', NULL, NULL),
	(369, 'TC', 'Turks and Caicos Islands', 'America/Grand_Turk', 'UTC -05:00', NULL, NULL),
	(370, 'TV', 'Tuvalu', 'Pacific/Funafuti', 'UTC +12:00', NULL, NULL),
	(371, 'UG', 'Uganda', 'Africa/Kampala', 'UTC +03:00', NULL, NULL),
	(372, 'UA', 'Ukraine', 'Europe/Kyiv', 'UTC +02:00', NULL, NULL),
	(373, 'UA', 'Ukraine', 'Europe/Simferopol', 'UTC +03:00', NULL, NULL),
	(374, 'AE', 'United Arab Emirates', 'Asia/Dubai', 'UTC +04:00', NULL, NULL),
	(375, 'GB', 'United Kingdom', 'Europe/London', 'UTC', NULL, NULL),
	(376, 'US', 'United States', 'America/Adak', 'UTC -10:00', NULL, NULL),
	(377, 'US', 'United States', 'America/Anchorage', 'UTC -09:00', NULL, NULL),
	(378, 'US', 'United States', 'America/Boise', 'UTC -07:00', NULL, NULL),
	(379, 'US', 'United States', 'America/Chicago', 'UTC -06:00', NULL, NULL),
	(380, 'US', 'United States', 'America/Denver', 'UTC -07:00', NULL, NULL),
	(381, 'US', 'United States', 'America/Detroit', 'UTC -05:00', NULL, NULL),
	(382, 'US', 'United States', 'America/Indiana/Indianapolis', 'UTC -05:00', NULL, NULL),
	(383, 'US', 'United States', 'America/Indiana/Knox', 'UTC -06:00', NULL, NULL),
	(384, 'US', 'United States', 'America/Indiana/Marengo', 'UTC -05:00', NULL, NULL),
	(385, 'US', 'United States', 'America/Indiana/Petersburg', 'UTC -05:00', NULL, NULL),
	(386, 'US', 'United States', 'America/Indiana/Tell_City', 'UTC -06:00', NULL, NULL),
	(387, 'US', 'United States', 'America/Indiana/Vevay', 'UTC -05:00', NULL, NULL),
	(388, 'US', 'United States', 'America/Indiana/Vincennes', 'UTC -05:00', NULL, NULL),
	(389, 'US', 'United States', 'America/Indiana/Winamac', 'UTC -05:00', NULL, NULL),
	(390, 'US', 'United States', 'America/Juneau', 'UTC -09:00', NULL, NULL),
	(391, 'US', 'United States', 'America/Kentucky/Louisville', 'UTC -05:00', NULL, NULL),
	(392, 'US', 'United States', 'America/Kentucky/Monticello', 'UTC -05:00', NULL, NULL),
	(393, 'US', 'United States', 'America/Los_Angeles', 'UTC -08:00', NULL, NULL),
	(394, 'US', 'United States', 'America/Menominee', 'UTC -06:00', NULL, NULL),
	(395, 'US', 'United States', 'America/Metlakatla', 'UTC -09:00', NULL, NULL),
	(396, 'US', 'United States', 'America/New_York', 'UTC -05:00', NULL, NULL),
	(397, 'US', 'United States', 'America/Nome', 'UTC -09:00', NULL, NULL),
	(398, 'US', 'United States', 'America/North_Dakota/Beulah', 'UTC -06:00', NULL, NULL),
	(399, 'US', 'United States', 'America/North_Dakota/Center', 'UTC -06:00', NULL, NULL),
	(400, 'US', 'United States', 'America/North_Dakota/New_Salem', 'UTC -06:00', NULL, NULL),
	(401, 'US', 'United States', 'America/Phoenix', 'UTC -07:00', NULL, NULL),
	(402, 'US', 'United States', 'America/Sitka', 'UTC -09:00', NULL, NULL),
	(403, 'US', 'United States', 'America/Yakutat', 'UTC -09:00', NULL, NULL),
	(404, 'US', 'United States', 'Pacific/Honolulu', 'UTC -10:00', NULL, NULL),
	(405, 'UM', 'United States Minor Outlying Islands', 'Pacific/Midway', 'UTC -11:00', NULL, NULL),
	(406, 'UM', 'United States Minor Outlying Islands', 'Pacific/Wake', 'UTC +12:00', NULL, NULL),
	(407, 'UY', 'Uruguay', 'America/Montevideo', 'UTC -03:00', NULL, NULL),
	(408, 'UZ', 'Uzbekistan', 'Asia/Samarkand', 'UTC +05:00', NULL, NULL),
	(409, 'UZ', 'Uzbekistan', 'Asia/Tashkent', 'UTC +05:00', NULL, NULL),
	(410, 'VU', 'Vanuatu', 'Pacific/Efate', 'UTC +11:00', NULL, NULL),
	(411, 'VE', 'Venezuela, Bolivarian Republic of', 'America/Caracas', 'UTC -04:00', NULL, NULL),
	(412, 'VN', 'Viet Nam', 'Asia/Ho_Chi_Minh', 'UTC +07:00', NULL, NULL),
	(413, 'VG', 'Virgin Islands, British', 'America/Tortola', 'UTC -04:00', NULL, NULL),
	(414, 'VI', 'Virgin Islands, U.S.', 'America/St_Thomas', 'UTC -04:00', NULL, NULL),
	(415, 'WF', 'Wallis and Futuna', 'Pacific/Wallis', 'UTC +12:00', NULL, NULL),
	(416, 'YE', 'Yemen', 'Asia/Aden', 'UTC +03:00', NULL, NULL),
	(417, 'ZM', 'Zambia', 'Africa/Lusaka', 'UTC +02:00', NULL, NULL),
	(418, 'ZW', 'Zimbabwe', 'Africa/Harare', 'UTC +02:00', NULL, NULL),
	(419, 'AX', 'Åland Islands', 'Europe/Mariehamn', 'UTC +02:00', NULL, NULL);
        ");
    }
}